### ISSUE TITLE
都mstsc了，再加这个是否多余？

### ISSUE THREAD

**Issue by codeex** [bobowire/Wireboy.Socket.P2PService#1]

**Comment by bobowire** [comment]
这是利用服务器进行数据转发，使得两个不同内网的电脑可以使用mstsc进行连接。
如下图，电脑A与电脑B处于不同的两个内网，不能直接连接，需要使用服务器进行数据中转。
[电脑A <-> 主控端] <-> [服务器] <-> [被控端 <-> 电脑B]

**Comment by codeex** [comment]
very good.
