### ISSUE TITLE
看日志的话你这个还是开了一个随机端口啊，能不能实现不额外开端口就可以直接访问的功能？

### ISSUE THREAD

**Issue by crazyNing** [bobowire/Wireboy.Socket.P2PService#12]
看日志的话你这个还是开了一个随机端口啊，能不能实现不额外开端口就可以直接访问的功能？

**Comment by crazyNing** [comment]
然后还有，模式五：限制客户端名称的AllowPort=3389:name这种方式我这边为什么起不来程序

**Comment by bobowire** [comment]
能不能实现不额外开端口就可以直接访问的功能？
答：最早的版本就是如此，但如果使用一个端口，在大量消耗网络宽带的时候，会造成程序的不稳定，并且会阻塞通信tcp，所以后面不再支持此种方式。

**Comment by crazyNing** [comment]
> ## 能不能实现不额外开端口就可以直接访问的功能？
> 答：最早的版本就是如此，但如果使用一个端口，在大量消耗网络宽带的时候，会造成程序的不稳定，并且会阻塞通信tcp，所以后面不再支持此种方式。
> 模式五：限制客户端名称的AllowPort=3389:name这种方式我这边为什么起不来程序
> 答：已测试，此为bug，后面将会修复，当然你也可以自己修复此问题。造成此bug的原因在于配置文件的读取。

好的，非常感谢您的回复，我去尝试一下修改，谢谢。

**Comment by bobowire** [comment]
模式五：限制客户端名称的AllowPort=3389:name这种方式我这边为什么起不来程序
答:en...我要重新回复一下此问题，程序正常启动，控制台是很简单的，只有在异常情况下，才会输出日志，所以，我怀疑你的程序应该已经正常启动了。如果没有控制台，请告诉我你的运行环境。

**Comment by bobowire** [comment]
关于是否已经正常启动，可以在同一个电脑，开启2个客户端进行端口测试

**Comment by crazyNing** [comment]
> 模式五：限制客户端名称的AllowPort=3389:name这种方式我这边为什么起不来程序
> 答:en...我要重新回复一下此问题，程序正常启动，控制台是很简单的，只有在异常情况下，才会输出日志，所以，我怀疑你的程序应该已经正常启动了。如果没有控制台，请告诉我你的运行环境。



![image](https://user-images.githubusercontent.com/40382918/69862256-f6ba6980-12d4-11ea-84f4-dc7fed7b9dc7.png)
配置文件是这样子设置的。不添加AllowPort的允许客户端名称时可以正常启动，添加之后，启动如下，我在同一台机器上开了三个配置一样的，但是都卡在这个页面，是我配置有问题嘛？我已经配置了日志级别为Debug
![image](https://user-images.githubusercontent.com/40382918/69862360-34b78d80-12d5-11ea-86aa-3d7323710440.png)

**Comment by crazyNing** [comment]
![image](https://user-images.githubusercontent.com/40382918/69862433-5a449700-12d5-11ea-9c7a-0ca9cfee611e.png)

![image](https://user-images.githubusercontent.com/40382918/69862448-629cd200-12d5-11ea-898a-00e3ec383656.png)

**Comment by bobowire** [comment]
目前本地测试正常，如果需要，可以加入首页介绍的QQ群寻求帮助

**Comment by crazyNing** [comment]
> 目前本地测试正常，如果需要，可以加入首页介绍的QQ群寻求帮助

好的，非常感谢
