### ISSUE TITLE
支持mac os吗？

### ISSUE THREAD

**Issue by jsls2517** [bobowire/Wireboy.Socket.P2PService#16]
如果支持的话，建议你编译一个mac os 版本并发布，这样会方便新手用户或不想弄编译环境的用户。

**Comment by bobowire** [comment]
支持，但木有mac的开发环境啊，哈哈哈哈哈

**Comment by WengJim** [comment]
好期待有mac的版本

**Comment by bobowire** [comment]
已经支持osx系统
https://github.com/bobowire/Wireboy.Socket.P2PSocket/releases
