### ISSUE TITLE
所以其实这个程序的功能并不只是远程控制是么？

### ISSUE THREAD

**Issue by Thiasap** [bobowire/Wireboy.Socket.P2PService#18]
我大概看了一下视频，就是将两个本地PC通过服务器进行流量中转，例如将PC机A的端口x与服务器S进行通信并S开放出y，相当于将A的x映射到S的y端口，然后B连接S的y相当于连接了A的x？如果是这样的话远程控制应该就只是其中的一个功能了
感觉像是个轻型VPN？给AB之间提供一个通信隧道

**Comment by bobowire** [comment]
没错 这个东西只是端口映射工具，远程控制以及其它的功能需要借助第三方工具，例如mstsc
