### ISSUE TITLE
Release版本能不能弄个编译好的

### ISSUE THREAD

**Issue by kamike** [bobowire/Wireboy.Socket.P2PService#19]
不是熟悉windows平台的开发，没有.net开发环境，只想直接用，下载P2PSocket-V2.0.5之后，发现没有说明文档里面的那些文件，不是很方便啊，感谢

**Comment by bobowire** [comment]
在released标签中有编译好的可执行程序

**Comment by bobowire** [comment]
关闭了
https://github.com/bobowire/Wireboy.Socket.P2PSocket/releases
