### ISSUE TITLE
是否可以在服务端开个端口接收，这样就只需要开home和服务端，不需要client了

### ISSUE THREAD

**Issue by smuki** [bobowire/Wireboy.Socket.P2PService#2]

**Comment by bobowire** [comment]
1.你可能有些误解了，此项目并不是远程控制项目，只是用于tcp数据转发
2.如果电脑可以与服务器直接连接，那么就不需要此项目进行中转了，通过mstsc可以直接连接服务器。
3.如果是为了将发送到服务器的请求转发到本机（例如：通过服务器转发将本地网站部署到公网），此功能将在后续更新中陆续支持。

**Comment by smuki** [comment]
我觉得是这样，将三个都合并成一个，然后通过参数启动，不管你是向要1，2，3 都可以通过命令行参数搞定。

**Comment by bobowire** [comment]
Home和Client合并在计划当中，感谢你的关注！
