### ISSUE TITLE
经过转发的TCP是否被限速，

### ISSUE THREAD

**Issue by qq40194386** [bobowire/Wireboy.Socket.P2PService#22]
**Is your feature request related to a problem? Please describe.**
转发的TCP流是否被限速，最好是不要限速
管道通讯是否指可以通过管道设置和取消指定TCP打洞对象和端口，是否可以通过管道获取本机CLIENTID,
服务器配置文件如果要求客户authcode登录是否用以下格式方便编辑，
[USER]
CLIENT1=PSW01
CLIENT2=PSW02
是否支持服务端 管道通讯添加登录客户端
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bobowire** [comment]
1.转发的TCP流速度，取决于你的服务器上下行带宽。
2.管道通讯，目前只在客户端增加了，可以通过它动态添加、修改、删除端口映射，打印日志等等，当然，你也可以自己扩展。
3.关于authcode授权这一块，后面会进行变动，无论是当前的authcode还是你的建议，似乎都不是很好，后面会考虑后再修改
