### ISSUE TITLE
配置文件中设置的都是P2P打洞的模式，为啥在服务器日志里面还是看到 通知客户端建立中转模式隧道

### ISSUE THREAD

**Issue by qq40194386** [bobowire/Wireboy.Socket.P2PService#23]
1.client配置文件能不能用以下来表示P2P打洞，这样可用写配置文件的方式操作这个文件
3008=1@[4222]:30000
2.这个程序从原理来讲，起一个代理服务器的作用，按道理其实是可以访问打洞另一方的局域网的资源的比如打洞另外一方的局域网的一台设备IP的指定端口 比如 以下的表示
3008=1@[4222#192.168.0.1]:80
本地的3008的端口访问重定向到4222这个ID的机器的局域网的192.168.0.1 这个IP的 80端口上
3.client能否开个监听UDP端口，接受 端口添加 改变，删除 操作。这样比管道方便的多
4.我明明全部设置的p2p打洞模式，为啥在服务器日志里面还有看到通知客户端建立中转模式
5.能否关闭日志，节省点资源

**Comment by bobowire** [comment]
问题一：可以通过插件，重写接口的方式实现此功能。
问题二：此开源项目只会进行核心功能的开发，你这种已经偏向业务，可以有2种方式达到你的目的。1.在主控端配置3008->1@[4222]:3008，在被控端配置3008->192.168.0.1:80 ，程序将会把电脑A的3008端口数据转发到192.168.0.1:80。2.可以通过在4222电脑中，搭建代理服务器，对代理服务器端口进行打洞连接，从而可以在电脑A使用4222电脑的代理服务器访问内网。
问题三：udp功能可以通过插件的方式，添加此功能
问题四：无论是不是p2p，都是要服务端配合的，所以会有相应的日志打印，这里是因为日志打印错误
问题五：日志等级可以自行在配置文件修改，具体可以参考wiki文档
