### ISSUE TITLE
两个客户端互相打洞，仅仅是因为端口不同，连接成功的比例相差很多

### ISSUE THREAD

**Issue by qq40194386** [bobowire/Wireboy.Socket.P2PService#24]
[PortMapItem]
3000->1@[9139]:8080
3009->1@[9139]:30000
3002->1@[9139]:5900

这个是客户端A的端口设置，映射了客户端9139的3个端口到本地，在网络不变的情况下，访问本地3002端口来访问远程5900 端口 这个是VNC的端口 连接成功率100%，访问其他两个端口，就算是LOG里面提示了端口复用成功，p2p隧道连接成功，也是马上接着连接断开这一句输出，很难连上是不是在处理连接的地方有不一样呢，客户端9139的端口设置是0-0 全部开的，客户端A的日志如下，可以看到连接上马上就断开了，另外两个端口一个是APACHE的端口，一个也是HTTP服务器的端口

:46:26:4125 >> 正在建立P2P模式隧道 token:ac30be18-a10c-4c5a-8904-f7e22d67a53a client:9139 port:30000
23:46:26:4395 >> 命令：0x0201  正尝试建立P2P模式隧道 token:ac30be18-a10c-4c5a-8904-f7e22d67a53a
23:46:26:4675 >> 命令：0x0201 P2P模式隧道，已连接到服务器，等待下一步操作 token:ac30be18-a10c-4c5a-8904-f7e22d67a53a
23:46:26:5205 >> 命令：0x0201 P2P模式隧道，端口复用成功 port:56379 token:ac30be18-a10c-4c5a-8904-f7e22d67a53a
23:46:26:5205 >> 命令：0x0201 P2P模式隧道，连接成功 token:ac30be18-a10c-4c5a-8904-f7e22d67a53a
23:46:26:5475 >> 正在建立P2P模式隧道 token:134d0c7b-7c96-41bb-8ff6-7a6389f01cbc client:9139 port:30000
23:46:27:4436 >> Tcp连接已被断开 49.84.56.39:25872
23:46:27:4436 >> 命令：0x0201  正尝试建立P2P模式隧道 token:134d0c7b-7c96-41bb-8ff6-7a6389f01cbc
23:46:27:4766 >> 命令：0x0201 P2P模式隧道，已连接到服务器，等待下一步操作 token:134d0c7b-7c96-41bb-8ff6-7a6389f01cbc
23:46:27:4766 >> Tcp连接已被断开 127.0.0.1:56378
23:46:27:4766 >> 正在建立P2P模式隧道 token:5b9a57cf-404c-4e5e-be18-576674d92653 client:9139 port:30000
23:46:27:9756 >> 命令：0x0201  正尝试建立P2P模式隧道 token:5b9a57cf-404c-4e5e-be18-576674d92653
23:46:28:0036 >> 命令：0x0201 P2P模式隧道，已连接到服务器，等待下一步操作 token:5b9a57cf-404c-4e5e-be18-576674d92653
23:46:28:0256 >> 命令：0x0201 P2P模式隧道，端口复用成功 port:56381 token:134d0c7b-7c96-41bb-8ff6-7a6389f01cbc
23:46:28:0256 >> 命令：0x0201 P2P模式隧道，连接成功 token:134d0c7b-7c96-41bb-8ff6-7a6389f01cbc
23:46:28:0486 >> 命令：0x0201 P2P模式隧道，端口复用成功 port:56384 token:5b9a57cf-404c-4e5e-be18-576674d92653
23:46:28:0486 >> 命令：0x0201 P2P模式隧道，连接成功 token:5b9a57cf-404c-4e5e-be18-576674d92653
23:46:28:0496 >> Tcp连接已被断开 49.84.56.39:25873
23:46:28:0496 >> Tcp连接已被断开 127.0.0.1:56380
23:46:28:0696 >> Tcp连接已被断开 127.0.0.1:56382
23:46:28:0696 >> Tcp连接已被断开 49.84.56.39:25874
23:46:28:5816 >> 正在建立P2P模式隧道 token:47a30faa-ac45-4b4b-8bc2-f929be566a8d client:9139 port:30000
23:46:28:6096 >> 命令：0x0201  正尝试建立P2P模式隧道 token:47a30faa-ac45-4b4b-8bc2-f929be566a8d
23:46:28:6376 >> 命令：0x0201 P2P模式隧道，已连接到服务器，等待下一步操作 token:47a30faa-ac45-4b4b-8bc2-f929be566a8d
23:46:28:6946 >> 命令：0x0201 P2P模式隧道，端口复用成功 port:56386 token:47a30faa-ac45-4b4b-8bc2-f929be566a8d
23:46:28:6946 >> 命令：0x0201 P2P模式隧道，连接成功 token:47a30faa-ac45-4b4b-8bc2-f929be566a8d
23:46:28:7196 >> Tcp连接已被断开 49.84.56.39:25875
23:46:28:7196 >> Tcp连接已被断开 127.0.0.1:56385

**Comment by bobowire** [comment]
程序是不会主动断开tcp的，具体断开的原因，可以查看客户端B的日志
