### ISSUE TITLE
部分机器无法P2P打洞互联的可能性

### ISSUE THREAD

**Issue by qq40194386** [bobowire/Wireboy.Socket.P2PService#25]
**Bug的描述**

>

> 有部分客户端之间无法P2P打洞互联，但是其中一个客户端和其他客户端是能P2P互联的，另外一个客户端和其他所有的也无法互联，但是程序启动显示是正常连上服务器的

**操作步骤**
抓包发现，无法互联的哪个客户端发包到其他端，都是被直接拒绝也就是RST ACK 包，即使端口复用成功的包发过来也是直接被拒绝，这样肯定是连不上了，我是在两台机器都是装了WIRESHARK里面看的到包的通讯，所以并不是路由器的防火墙拦截

**你所期望的结果**
1. 打开 '...'
2. 输入 '....'
3. 点击 '....'
4. 成功连接远程桌面

**bug截图**
这个都传不上图片，需要图片的加我QQ 993924551传

**其它想说的**
关于bug的其它想法，可以在这里说明

**Comment by crazyNing** [comment]
有QQ群的哦，可以加群修复BUG

**Comment by bobowire** [comment]
1.端口服用成功并不是说就一定能打洞成功。
2.是否打洞成功和网络、路由、Nat都有一定关系
3.成功不了，那你只能使用转发模式了
