### ISSUE TITLE
提交一个功能/项目的改进建议

### ISSUE THREAD

**Issue by qq40194386** [bobowire/Wireboy.Socket.P2PService#26]
经过实际测试，在2台电脑之间，五个线程连接互相发送数据是很稳定的，基本上总速度在1M以上，但是，如果一对多个电脑，1台电脑同时对多个电脑同时各建立5个连接，传输速度马上就降低到卡死

**Comment by bobowire** [comment]
首先，感谢你的反馈，为帮助排查问题，需要知道当前发现问题的程序版本号，请提供一下。
另外，中转模式传输速度受限于服务带宽，“降低到卡死”是什么情况？如果多个tcp都存在大量的数据传输，你可以在“1对多”的“1”中查看总的传输速度。

**Comment by bobowire** [comment]
另外，为方便沟通，可以加入ReadMe中提供的QQ群，在群里提出所遇到的问题

**Comment by qq40194386** [comment]
群加了很多次都加不进去。程序是最新版，系统是WIN7 64位，两台电脑之间 建立5个TCP 连接是很稳定的，持续数据传输1M 每秒很稳定，也就是一个TCP连接200K的样子，但是如果这两台电脑同时建立10个连接，也是一样不稳定的
