### ISSUE TITLE
P2P服务器端运行一段时间后挂掉

### ISSUE THREAD

**Issue by fansxs** [bobowire/Wireboy.Socket.P2PService#27]
**Bug的描述**
P2P服务器端一直运行在服务器，Windows Server 2008，客户端不进行任何连接，一段时间后，P2P服务器端挂了，打印日志显示别人的IP有进行尝试连接，并且有“非法的TCP数据包”，猜测应该是别人在对网络上的主机进行端口扫描造成的吧，毕竟有很多人的电脑挂机就是为了扫描网络上的主机。

**其它想说的**
非常感谢楼主能编写并开源这个非常棒的项目: :+1: ！另外群加了几次一直没加进去

**Comment by bobowire** [comment]
这个bug前段时间已经在dev分之修复过了，如果需要，可以自行下载dev分之的源码编译。另外，QQ群加不进去是什么原因？我看了最近的加群记录，并没有拒绝的操作

**Comment by fansxs** [comment]
好的呢，非常感谢 :)，我试下。

**Comment by fansxs** [comment]
加QQ群我知道什么原因了，之前我一直都是用TIM加的，可能是TIM的BUG，用QQ一加就加进去了！腾讯这么大一公司居然会存在这样严重的BUG @_@

**Comment by pinfer** [comment]
为啥打洞模式连不上,转发可以连上

**Comment by bobowire** [comment]
> 为啥打洞模式连不上,转发可以连上

受限于路由器、运营商、NAT限制等等，不是你我能够控制的
