### ISSUE TITLE
想从外网访问内网数据库

### ISSUE THREAD

**Issue by yss0729** [bobowire/Wireboy.Socket.P2PService#33]
请教下，想从外网访问内网数据库，要怎么配置

**Comment by ni-xue** [comment]
需要先将内网 映射到广域网上，这样就是 外对外了

**Comment by bobowire** [comment]
在服务器配置文件中，参考以下进行配置
6978->[ClientA]:6666

把内网6666端口映射到服务器端口6978，外网连接服务器的6978即可
