### ISSUE TITLE
-bash: ./P2PSocket.StartUp: 无法执行二进制文件: 可执行文件格式错误提交一个BUG帮助我们完善项目

### ISSUE THREAD

**Issue by ogreatary** [bobowire/Wireboy.Socket.P2PService#39]
linux服务端启动失败
-bash: ./P2PSocket.StartUp: 无法执行二进制文件: 可执行文件格式错误

**Comment by bobowire** [comment]
这应该是执行错了文件，或者使用的版本不兼容当前linux系统吧

**Comment by ogreatary** [comment]
如下是详情。不兼容吗？
Linux root 4.18.0-240.22.1.el8_3.x86_64 #1 SMP Thu Apr 8 19:01:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ogreatary** [comment]
是执行P2PSocket.StartUp  这个文件对吧？

**Comment by bobowire** [comment]
> 

文件是对的，不同的linux有不同的cpu型号，这个也得对应上，看你这架构是x86_64的，但是提供包里好像都是arm架构的
