### ISSUE TITLE
提问,安卓的手机怎么能远程?

### ISSUE THREAD

**Issue by xman55555** [bobowire/Wireboy.Socket.P2PService#6]
**在使用过程中有了更好的想法？请在这里告诉我们.**
在这里描述你的想法，例如：在使用xxx的时候，我发现这样做能更舒服...
安卓的手机能远程么?

**Comment by bobowire** [comment]
这不是一个远程工具，远程控制电脑或者手机，你需要使用第三方工具，例如：teamview
此工具仅用于内网的数据包转发。
