### ISSUE TITLE
提交一个功能/项目的改进建议

### ISSUE THREAD

**Issue by mikemikemikecai** [bobowire/Wireboy.Socket.P2PService#7]
**在使用过程中有了更好的想法？请在这里告诉我们.**
在这里描述你的想法，例如：在使用xxx的时候，我发现这样做能更舒服...

提供一个改进意见；
p2p直连可能是个坑，公司内的防火墙分分钟把你卡死，建议不做考虑。

建议完善服务端，双击运行客户端自动连接服务端反馈主机信息，确定连接端口，服务端登记并通过web后台显示在线详情。

**Comment by bobowire** [comment]
目前已经放弃P2P打洞，全部使用服务器转发数据的方式实现内网穿透了。
至于服务端登记等功能，已在更新计划之中，敬请期待，也可pull requestes
