### ISSUE TITLE
NTLM Authentication

### ISSUE THREAD

**Issue by hez2010** [bobowire/Wireboy.Socket.P2PService#8]
请问使用该程序进行 http 服务内网穿透是否支持穿透 NTLM Authentication？

**Comment by bobowire** [comment]
这只是一个端口数据转发的程序，所以支持任何基于tcp协议下程序，所以NTLM如果是基于tcp协议，则可以支持

**Comment by hez2010** [comment]
NTLM是基于tcp的，但是它是stateful的需要agent keepalive

**Comment by bobowire** [comment]
1.任何使用tcp协议进行通讯的程序均可以使用此程序进行内网穿透。
2.利用此程序进行内网穿透的各种软件，使用时，逻辑无需变更。

**Comment by bobowire** [comment]
关闭喽
